import Head from 'next/head'
import Header from '../../components/header'
import Movies from '../../components/movies'
import { useState, useEffect } from 'react';
import { latest } from '../../actions/movies'

export default function Home() {

  const [data,setData] = useState({})

    useEffect(() => {   
        latest().then(data =>{
        setData(data.results)
        })
    },[])

  return (
    <div>
      <Head>
        <title>Capital Movies</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Header />
        <Movies data={data} />
      </main>

    </div>
  )
}
