import Head from 'next/head'
import SignupComponent from '../components/auth/SignupComponent'
import Header from '../components/header'

export default function Login() {

  return (
    <div>
      
      <Head>
        <title>Capital Movies</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Header />
        <div className="container-fluid p-4" style={{'color':'white','marginTop':'60px'}}>
        <div className="col-lg-4 offset-lg-4" style={{'backgroundColor':'gray'}}>
                <h2 className="text-center pt-4">Signup</h2>
                <div className="row">
                        <SignupComponent />
                    </div>
                </div>
            </div>
      </main>

    </div>
  )
}
